// ASM_INC_DATA_POINTER: 'inc esi',
//     ASM_ADD_DATA_POINTER: 'add esi, ',
//     ASM_DEC_DATA_POINTER: 'dec esi',
//     ASM_SUB_DATA_POINTER: 'sub esi, ',
//     ASM_INC_DATA: 'inc byte ptr [esi]',
//     ASM_ADD_DATA: 'add byte ptr [esi], ',
//     ASM_DEC_DATA: 'dec byte ptr [esi]',
//     ASM_SUB_DATA: 'sub byte ptr [esi], ',
//     ASM_CALL_DISPLAY_CURRENT_BYTE: 'call displayCurrentByte',
//     ASM_CALL_READ_CURRENT_BYTE: 'call readCurrentByte',
//     ASM_WHILE_NOT_ZERO_LABEL: 'whileNotZero',
//     ASM_WHILE_NOT_ZERO: 'cmp byte ptr [esi], 0',
//     ASM_WHILE_NOT_ZERO_JUMP: 'je endWhileNotZero',
//     ASM_END_WHILE_JUMP: 'jmp whileNotZero',
//     ASM_END_WHILE_LABEL: 'endWhileNotZero',
//     ASM_END_LABEL: ':',
//     ASM_COMMENT: '; ',
//     ASM_NEW_LINE: '\n',
